<div class="zend_form">
    <?php  echo $this->formMatiere; ?>
</div>

<?php if($this->send) : ?>
<table class="display" id="datatable">
    <thead>
        <tr>
            <th>n°</th>
            <th>n° conteneur</th>
            <th>Adresse</th>
            <th>Commune</th>
            <th>Tonnage</th>
            <!--<th>Nb relevés</th>-->
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>n°</th>
            <th>n° conteneur</th>
            <th>Adresse</th>
            <th>Commune</th>
            <th>Tonnage</th>
            <!--<td>Nb relevés</td>-->
        </tr>
    </tfoot>
    <tbody>
    <?php
        $i = 1;
        foreach($this->infosConteneur as $unSite)
        {
            echo '<tr>
                    <td>'.$i.'</td>
                    <td>'.$unSite['NO_CONTENEUR'].'</td>
                    <td>'.$unSite['NOM_SITE'].', '.$unSite['LOC_SITE'].'</td>
                    <td>'.$unSite['NOM_COMMUNE'].'</td>
                    <td>'.$unSite['QTE'].'</td>
                    <!--<td>'.$unSite['ID_SITE'].'</td>-->
                </tr>';
            $i++;
        }
        
    ?>
    </tbody>
</table>   
<script type="text/javascript">
$(document).ready(function() {
   $('#datatable').dataTable({
        "bJQueryUI": true,
        "sPaginationType": "full_numbers"
    });
});
</script>
<?php endif; ?>