<h2>Statistiques pour une période</h2>
<div id="divPalmares">
    <?php  echo $this->formMatiere; ?>
</div>
<?php if($this->send) : ?>
<p>
    Statistiques pour les conteneurs <?php echo strtolower($this->matiere); ?>
    pour la periode du <?php echo $this->dateDebut; ?> au <?php echo $this->dateFin;?>
</p>

<table class="display" id="datatable">
    <thead>
        <tr>
            <th>n°</th>
            <th>n° conteneur</th>
            <th class="thadresse">Adresse</th>
            <th class="thcommune">Commune</th>
            <th>Tonnage</th>
            <th>Nb relevés</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>n°</th>
            <th>n° conteneur</th>
            <th>Adresse</th>
            <th>Commune</th>
            <th>Tonnage</th>
            <th>Nb relevés</th>
        </tr>
    </tfoot>
    <tbody>
    <?php
        $i = 1;
        foreach($this->infosConteneur as $unSite)
        {
             echo '<tr class="gradeA">
                        <td>'.$i.'</td>
                        <td>'.$unSite['NO_CONTENEUR'].'</td>
                        <td>'.ucwords(strtolower($unSite['NOM_SITE']));//
                        if($unSite['LOC_SITE'] != '')
                        {
                            echo ', '.ucwords(strtolower($unSite['LOC_SITE']));
                        }
                  echo '</td><td>'.ucwords(strtolower($unSite['NOM_LOCALITE'])).'</td>
                        <td>'.$unSite['QTE'].'</td>
                        <td>'.$unSite['LEVEES'].'</td>
                    </tr>';
            $i++;
        }
        
    ?>
    </tbody>
</table> 
<script type="text/javascript">
$(document).ready(function() {
   $('#datatable').dataTable({
        "bJQueryUI": true,
        "sPaginationType": "full_numbers"
    });
});
</script>

<?php else: ?>
    <p id="msgStats">Selectionnez une matiere et une periode pour obtenir les statistiques</p>
<?php endif; ?>