<?php if($this->creerPdf != 'ok') :  ?>

<h2>Statistiques pour une période</h2>
<div id="divPalmares">
    <?php  echo $this->formMatiere; ?>
    <?php 
        if($this->send): 
            $dd = str_replace('/', '-', $this->dateDebut);
            $df = str_replace('/', '-', $this->dateFin);
    ?>
    <div id="removeBouton">
       <!-- on met le bouton de generation de pdf -->
       <form method="post" action="<?php echo $this->baseUrl('/palmares/infosperiode/radioMatiere/'.$this->matiere);?>/dd/<?php echo $dd; ?>/df/<?php echo $df; ?>" >
            <input type="hidden" name="creerPdf" value="ok">
            <input type="submit" value="PDF" onclick="creationpdf(this);" >
        </form>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php if($this->send) : ?>
        <p id="annonceStats">
            Statistiques pour les conteneurs <?php echo strtolower($this->matiere); ?>
            pour la période du <?php echo $this->dateDebut; ?> au <?php echo $this->dateFin;?>
        </p>

        <table class="display" id="datatable">
            <thead>
                <tr>
                    <th>N°</th>
                    <th>N° Site</th>
                    <th>Adresse</th>
                    <th>Commune</th>
                    <th>Tonnage</th>
                    <th>Nb relevés</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>N°</th>
                    <th>N° Site</th>
                    <th>Adresse</th>
                    <th>Commune</th>
                    <th>Tonnage</th>
                    <th>Nb relevés</th>
                </tr>
            </tfoot>
            <tbody>
            <?php
                $i = 1; $total = 0;
                foreach($this->infosSite as $unSite)
                {
                     echo '<tr class="gradeA">
                                <td>'.$i.'</td>
                                <td>'.$unSite['ID_SITE'].'</td>
                                <td>'.ucfirst(strtolower($unSite['NOM_SITE']));
                                if($unSite['LOC_SITE'] != '')
                                {
                                    echo ', '.utf8_encode(ucfirst(strtolower($unSite['LOC_SITE'])));
                                }
                          echo '</td><td>'.ucfirst(strtolower($unSite['NOM_LOCALITE'])).'</td>
                                <td>'.$unSite['QTE'].'</td>
                                <td>'.$unSite['LEVEES'].'</td>
                            </tr>';
                    $i++;
                    $qte = str_replace(',', '.', $unSite['QTE']);
                    $total += $qte;
                }

            ?>
            </tbody>
        </table> 
       <p id="totaux">
           <span id="ttotal"></span> 
           (<?php echo $total;?> Total)
       </p>
       
       <script type="text/javascript">
           $(document).ready(function() {
                doDatatables({ "sType": "numeric-comma" });
           });
       </script>
<?php 
    else:
        if($this->creerPdf == 'ok') : 
        
            $dd = str_replace('/', '-', $this->dateDebut);
            $df = str_replace('/', '-', $this->dateFin);
        
            ob_start();
    ?>
    <style type="text/css">
        th { border: 1px solid black; }
        td { border : .1px solid black; padding : 5px;}
    </style>
    <page backtop="20mm" backbottom="10mm">
        <page_header><h1 style="text-align:center;">Statistiques <?php echo $this->dateDebut.' : '.$this->dateFin; ?></h1><hr></page_header>
        <page_footer> <hr>
            <p style="text-align:center;">stats_<?php echo $dd;?>_<?php echo $df;?>.pdf |
                <?php echo new Zend_Date; ?>
            </p>
        </page_footer>
        <br />
        <table cellpadding="0" cellspacing="0" style="width: 100%; border: 1px solid black; background: #E7E7E7; text-align: center; font-size: 10pt;">
            <thead>
                <tr>
                    <th style="width: 5%">N°</th>
                    <th style="width: 10%">N° Site</th>
                    <th style="width: 50%">Adresse</th>
                    <th style="width: 15%">Commune</th>
                    <th style="width: 10%">Tonnage</th>
                    <th style="width: 10%">Nb relevés</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th style="width: 5%">N°</th>
                    <th style="width: 10%">N° Site</th>
                    <th style="width: 50%">Adresse</th>
                    <th style="width: 15%">Commune</th>
                    <th style="width: 10%">Tonnage</th>
                    <th style="width: 10%">Nb relevés</th>
                </tr>
            </tfoot>
            <tbody>
            <?php
                $i = 1;
                foreach($this->infosSite as $unSite)
                {
                     echo '<tr>
                                <td style="width: 5%">'.$i.'</td>
                                <td style="width: 10%">'.ucfirst(strtolower($unSite['ID_SITE'].'</td>
                                <td style="text-align: left; width: 50%; padding-left : 5px;">'.$unSite['NOM_SITE']));
                                if($unSite['LOC_SITE'] != '')
                                {
                                    echo ', '.utf8_encode(ucfirst(strtolower($unSite['LOC_SITE'])));
                                }
                          echo '</td>
                                <td style="text-align: left; width: 15%">'.ucfirst(strtolower($unSite['NOM_LOCALITE'])).'</td>
                                <td style="width: 10%">'.$unSite['QTE'].'</td>
                                <td style="width: 10%">'.$unSite['LEVEES'].'</td>
                            </tr>';
                    $i++;
                }

            ?>
            </tbody>
        </table> 
    </page>
    <?php 
        $content = ob_get_clean();
        ob_end_clean();
        require_once($_SERVER['DOCUMENT_ROOT'].'/dma/public/html2pdf/html2pdf.class.php');
        $html2pdf = new HTML2PDF('P', 'A4', 'fr');
        // ecris l'html dans un document pdf
        $html2pdf->writeHTML($content);
        // affiche le pdf en lui donnant un nom
        $html2pdf->Output('stats_'.$dd.'_'.$df.'.pdf');
        exit; 
        
        else: 
    ?>
    <p class="infos">Sélectionnez une matieèe et une période pour obtenir les statistiques</p>
    <?php endif; ?>
    
<?php endif; ?>