<?php
    $class = 'bis';
    if(!$this->ajax)
        $class = 'prems';
    
    // si on a cliqué sur le bouton de generation de pdf
    if($this->creerPdf == 'ok') :
        ob_start(); // on commence l'enregistrement de l'html qui suit
?>
        <style type="text/css">
            th { border: 1px solid black; }
            td { border : .1px solid black; padding : 5px;}
        </style>
        <page backtop="20mm" backbottom="10mm">
            <page_header>
                <h1 style="text-align:center;">Statistiques <?php echo $this->matiere;?></h1>
                <hr>
            </page_header>
            <page_footer>
                <hr>
                <p style="text-align:center;">stats.pdf |
                    <?php echo new Zend_Date; ?>
                </p>
            </page_footer>
            <br>
            <table cellpadding="0" cellspacing="0" style="width: 100%; border: 1px solid black; background: #E7E7E7; text-align: center; font-size: 10pt;">
                <thead>
                    <tr>
                        <th style="width: 5%">N°</th>
                        <th style="width: 10%">N° Site</th>
                        <th style="width: 50%">Adresse</th>
                        <th style="width: 15%">Commune</th>
                        <th style="width: 10%">Tonnage</th>
                        <th style="width: 10%">Nb relevés</th>
                     </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th style="width: 5%">N°</th>
                        <th style="width: 10%">N° Site</th>
                        <th style="width: 50%">Adresse</th>
                        <th style="width: 15%">Commune</th>
                        <th style="width: 10%">Tonnage</th>
                        <th style="width: 10%">Nb relevés</th>
                    </tr>
                </tfoot>
                <tbody>
                <?php
                    $i = 1;
                    foreach($this->infosSite as $unSite)
                    {
                        echo '<tr>
                                <td style="width: 5%">'.$i.'</td>
                                <td style="width: 10%">'.ucfirst(strtolower($unSite['ID_SITE'].'</td>
                                <td style="text-align: left; width: 50%; padding-left : 5px;">'.$unSite['NOM_SITE']));
                                if($unSite['LOC_SITE'] != '')
                                {
                                    echo ', '.utf8_encode(ucfirst(strtolower($unSite['LOC_SITE'])));
                                }
                          echo '</td>
                                <td style="text-align: left; width: 15%">'.ucfirst(strtolower($unSite['NOM_LOCALITE'])).'</td>
                                <td style="width: 10%">'.$unSite['QTE'].'</td>
                                <td style="width: 10%">'.$unSite['LEVEES'].'</td>
                            </tr>';
                        $i++;
                    }
                ?>
            </tbody>
        </table>
    </page>
<?php 
    // on termine le flux html et on l'enregistre
    $content = ob_get_clean();
    ob_end_clean();
    require_once($_SERVER['DOCUMENT_ROOT'].'/dma/public/html2pdf/html2pdf.class.php');
    $html2pdf = new HTML2PDF('P', 'A4', 'fr');
    // ecris l'html dans un document pdf
    $html2pdf->writeHTML($content);
    // affiche le pdf en lui donnant un nom
    $html2pdf->Output('stats.pdf');
    exit;
    
    // on arrive sur la page de facon "normale"
    else : 
?>
    <div id="removeBouton"> <!-- on met le bouton de generation de pdf -->
       <form method="post" action="<?php echo $this->baseUrl('/palmares/infos/radio/'.$this->matiere); ?>" >
            <input type="hidden" name="creerPdf" value="ok">
            <input type="submit" value="PDF" onclick="creationpdf(this);" >
        </form>
    </div>
       <!-- on refait le code de la page sans le css spécifique au pdf    -->
        <div id="recup">
            <table id="datatable" class="<?php echo $class; ?> display">
             <thead>
                    <tr>
                        <th>N°</th>
                        <th>N° Site</th>
                        <th>Adresse</th>
                        <th>Commune</th>
                        <th>Tonnage</th>
                        <th>Nb relevés</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>N°</th>
                        <th>N° Site</th>
                        <th>Adresse</th>
                        <th>Commune</th>
                        <th>Tonnage</th>
                        <th>Nb relevés</th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php
                        $i = 1; $total = 0;
                        foreach($this->infosSite as $unSite)
                        {
                            echo '<tr class="gradeA">
                                    <td>'.$i.'</td>
                                    <td>'.$unSite['ID_SITE'].'</td>
                                    <td>'.ucfirst(strtolower($unSite['NOM_SITE']));
                                    if($unSite['LOC_SITE'] != '')
                                    {
                                        echo ', '.utf8_encode(ucfirst(strtolower($unSite['LOC_SITE'])));
                                    }
                              echo '</td>
                                    <td>'.ucfirst(strtolower($unSite['NOM_LOCALITE'])).'</td>
                                    <td>'.$unSite['QTE'].'</td>
                                    <td>'.$unSite['LEVEES'].'</td>
                                </tr>';
                            $i++;
                            $qte = str_replace(',', '.', $unSite['QTE']);
                            $total += $qte;
                        }
                    ?>
                </tbody>
            </table>
            <p id="totaux">
               <span id="ttotal"></span> 
               sur <?php echo $total;?> T
           </p>
        </div>
       <script type="text/javascript">
           $(document).ready(function() {
                doDatatables({ "sType": "numeric-comma" });
           });
       </script>
   <?php endif; ?>
<?php  if($this->ajax) exit; ?>