<?php
    $class = 'bis';
    if(!$this->ajax)
        $class = 'prems';
?>
<div id="recup">
    <table id="datatable" class="<?php echo $class; ?> display">
     <thead>
            <tr>
                <th>n°</th>
                <th>n° conteneur</th>
                <th class="thadresse">Adresse</th>
                <th class="thcommune">Commune</th>
                <th>Tonnage</th>
                <th>Nb relevés</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>n°</th>
                <th>n° conteneur</th>
                <th>Adresse</th>
                <th>Commune</th>
                <th>Tonnage</th>
                <th>Nb relevés</th>
            </tr>
        </tfoot>
        <tbody>
            <?php
                $i = 1;
                foreach($this->infosConteneur as $unSite)
                {
                    echo '<tr class="gradeA">
                            <td>'.$i.'</td>
                            <td>'.$unSite['NO_CONTENEUR'].'</td>
                            <td>'.ucwords(strtolower($unSite['NOM_SITE']));
                            if($unSite['LOC_SITE'] != '')
                            {
                                echo ', '.utf8_encode(ucfirst(strtolower($unSite['LOC_SITE'])));
                            }
                      echo '</td>
                            <td>'.ucwords(strtolower($unSite['NOM_LOCALITE'])).'</td>
                            <td>'.$unSite['QTE'].'</td>
                            <td>'.$unSite['LEVEES'].'</td>
                        </tr>';
                    $i++;
                }
            ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
// applique le datatable 
// on le met ici car il faut le réexcuter a chaque changement de tableau
// verre couleur -> papier/carton, etc...
$(document).ready(function() {
   $('#datatable').dataTable({
        "bJQueryUI": true,
        "sPaginationType": "full_numbers"
    });
});
</script>
<?php if($this->ajax) exit; ?>