<h2>Sites à utiliser</h2>

<div id="adminSites">
<p class="infos">Cochez ou décochez un site pour le prendre ou non en compte dans les statistiques</p>
    <table id="datatable" class="display">
         <thead>
                <tr>
                    <th>n°</th>
                    <th>n° site</th>
                    <th>Adresse</th>
                    <th>Commune</th>
                    <th>Utiliser ?</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>n°</th>
                    <th>n° site</th>
                    <th>Adresse</th>
                    <th>Commune</th>
                    <th>Utiliser ?</th>
                </tr>
            </tfoot>
            <tbody>
                <?php
                    $i = 1;
                    foreach($this->sites as $unSite)
                    {
                        echo '<tr class="gradeA">
                                <td>'.$i.'</td>
                                <td>'.$unSite['ID_SITE'].'</td>
                                <td>'.$unSite['NOM_SITE'];
                                if($unSite['LOC_SITE'] != '')
                                {
                                    echo ', '.utf8_encode($unSite['LOC_SITE']);
                                }
                            echo '</td><td>'.$unSite['NOM_COMMUNE'].'</td>';

                            $checked = $unSite['STAT_SITE'] == 1 ? 'checked="checked"' : '';
                            echo '<td id="cont_'.$i.'" class="tdcb">
                                    <input class="cbsite" type="checkbox" name="cbsites[]" value="'.$unSite['ID_SITE'].'" '.$checked.' />
                                </td>';
                        echo '</tr>';
                        $i++;
                    }
                ?>
            </tbody>
    </table>
    </div>
<script type="text/javascript">
$(document).ready(function() {
   $('#datatable').dataTable({
        "bJQueryUI": true,
        "sPaginationType": "full_numbers"
    });
});
</script>