
<?php echo $this->fcommunes; ?>

<!-- si on a une erreur -->
<?php if($this->erreur) : ?>
    <div id="erreurGraph"><p><?php echo $this->erreur; ?></p></div>
<?php endif; ?>
    
    <!-- le div dans lequel sera mis le graphique une fois généré -->
    <div id="chart_div" ></div>
    
    <!-- recupere l'api   -->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">      
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
      
        <?php 
            
            if($this->filtreUneCommune)
            {
                $libelle = 'NOM_EMPLACEMENT';
                if($this->nomCommune != '') {
                  $title = "'Tonnage par commune ($this->nomCommune)'";
                }
                else {
                  $title = "'Erreur! Commune introuvable'";
                }
            }
            else 
            {
                $libelle = 'NOM_COMMUNE';
                $title = "'Toutes les communes'";
            }
        ?>
      
      
        var wrapper = new google.visualization.ChartWrapper({
          chartType: 'ColumnChart',
          dataTable: [
              ['', <?php 
                $data ="";
                $max = count($this->tonnage);
                $i = 1;
                foreach($this->tonnage as $site)
                {
                  $data .= "'".addslashes(utf8_encode($site[$libelle]))."'";
                  $data .= $i == $max ? "]," : ",";
                  $i++;
                }
                $i = 1;
                $data .= "['',";
                foreach($this->tonnage as $site)
                {
                  $qte = str_replace(",", ".", $site['QTE']);
                  $data .= round($qte);
                  $data .= $i == $max ? '' : ',';
                  $i++;
                }
                echo $data;
              ?>                
            ]],
          options: {
            title : <?php echo $title;?>,
            height : '100%',
            chartArea: { height:"70%", left:40 },
            legend : { textStyle: { fontSize : 15 }},
            titleTextStyle : { fontSize : 20 }, 
            tooltip : { showColorCode : true }
          },
          containerId: 'chart_div'
        });
        
        wrapper.draw();
      }
      
      
      
</script>
