<h2>Importer un fichier csv</h2>
<?php echo $this->formFichier; ?>

<a id="sup_lignes" href="<?php echo $this->baseUrl('index/suplignes');?>" >Supprimer des enregistrements</a>
<div class="both"></div>

<?php 
    if($this->mode == 'verif') {
        if($this->failure) {
            echo '<h3 id="h3verif-e">Le fichier contient des erreurs !</h3>';
            echo '<table class="tb_errFic">';
            foreach ($this->err_fail as $nLig => $err) {
                echo '<tr>
                        <td class="td_err">
                            <span class="e-icon"></span>
                            Ligne n°'.$nLig.'</td>
                        <td>';
                foreach($err as  $e) {
                    echo '<table class="soustb_errFic">
                                <tr>
                                    <td>'.$e.'</td>
                                </tr>
                            </table>';
                }
                echo '</td></tr>';
            }
            echo '</table>';
        } else {
            echo '<h3 id="h3verif-s">Fichier correct !</h3>';
            if(!empty($this->tot_par_insee)) {
                echo '<p class="infos margin10">Récapitulatif des tonages et nombre de lignes insérées par numéro INSEE</p>';
                echo '<table class="datatable" id="tb_insee">
                    <thead>
                        <tr>
                            <td>Numero INSEE</td>
                            <td>Nombre de lignes</td>
                            <td>Tonnage</td>
                        </tr>
                    </thead>
                    <tbody>
                        ';
                foreach ($this->tot_par_insee as $insee => $tot_insee) {
                    echo '<tr>
                            <td>'.$insee.'</td>
                            <td>'.$tot_insee['nb'].'</td>
                            <td>'.$tot_insee['tot'].'</td>
                        </tr>';
                }
                echo '</tbody></table>';
            }
        }
        
        
        if(!empty($this->absents)) {
            if($this->matiere == 'Verre') {
                $type = 'cont';
            } else {
                $type = 'site';
            }
            echo '<p id="pcont">Les informations suivantes ont étés trouvées mais ne sont pas connues dans la base.</p>
                  <span id="spcont"> Cliquez dessus pour les ajouter avant d\'importer le fichier : </span>';
            
            echo '<ul class="left" id="ulcont">';
            foreach ($this->absents as $absent) {
                echo '<li class="licont"><a href="'.$this->baseUrl('/index/nouveausite/'.$type.'/'.$absent).'">'.$absent.'</a></li>';
            }
            echo '</ul>';
        }
    }
    else {
?>
    

        <?php
            // si on a une erreur, on l'affiche
            if($this->erreur) :
        ?>
            <div id="erreurFichier">
                <p><?php echo $this->erreur; ?></p>
            </div>

            <?php
                // sinon, si erreur n'est pas null (a false), on affiche le resultat de la requete
                elseif(!is_null($this->erreur)) : 
            ?>

            <div id="infosImport">
                <h3>Importation terminée avec succès !</h3>
                <p><?php echo $this->nbLignesSupp;?> ligne(s) supprimée(s)</p>
                <p><?php echo $this->nbNouvellesLignes;?> ligne(s) ajoutée(s)</p>
                <p>Tonnage total : <?php echo $this->total;?></p>
            </div>
        <?php else: ?>
            <p class="infos" id="geneIE">L'importation d'un fichier csv entraine la suppression des anciennes données</p>
        <?php endif; ?>
    <?php }?>

<script type="text/javascript">
    $(document).ready(function() {
         $('.datatable').dataTable({
            "bJQueryUI": true,  // ajoute le style par defaut (jqueryUI) sur la table
            // affiche une information de chargement de la table si trop longue a charger
            "bProcessing" : true,
            "iDisplayLength" : -1,
            "bLengthChange": false, // empeche de changer le nombre de lignes a afficher
            "bPaginate" : false,    // retire les boutons de navigation des pages (on en a plus qu'une)
            "bFilter" : false,  // retire le champ de recherche
            "bSort" : false,
            "bInfo" : false    // retire les infos inutiles ici
         });
         $('.fg-toolbar').remove();
         $('#tb_insee_wrapper').css('width', '100%');
    });
</script>