<h2>Importer un fichier csv</h2>
<?php echo $this->formFichier; ?>
<div class="both"></div>
<?php
    // si on a une erreur, on l'affiche
    if($this->erreur) :
?>
    <div id="erreurFichier">
        <p><?php echo $this->erreur; ?></p>
    </div>

    <?php
        // sinon, si erreur n'est pas null (a false), on affiche le resultat de la requete
        elseif(!is_null($this->erreur)) : 
    ?>

    <div id="infosImport">
        <h3>Importation terminée avec succès !</h3>
        <p><?php echo $this->nbLignesSupp;?> ligne(s) supprimée(s)</p>
        <p><?php echo $this->nbNouvellesLignes;?> ligne(s) ajoutée(s)</p>
    </div>
<?php else: ?>
    <p class="infos" id="geneIE">L'importation d'un fichier csv entraine la suppression des anciennes données</p>
<?php endif; ?>
