<h2>Nouveau site</h2>
<?php 
    echo $this->fnvsite;
    
    if($this->send) : 
        if($this->message) :
?>
        <div><h4><?php echo $this->message;?></h4></div>
    <?php endif; ?>
    
    <div id="ajoutSite">
        <p>Conteneur n° <?php echo $this->donnees['NO_CONTENEUR'];?></p>
        <p>Site n° <?php echo $this->donnees['ID_SITE'];?></p>
        <p>
            Adresse : <?php echo utf8_encode($this->donnees['NOM_EMPLACEMENT']);?>
            (<?php echo utf8_encode($this->complement);?>)
        </p>
    </div>
<?php endif; ?>
