<!DOCTYPE>
<html>
    <head>
        <title>DMA</title>
        <meta charset="utf-8" />
        <!--[if lte IE 8]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <!--<script type="text/javascript" src="https://getfirebug.com/firebug-lite.js"></script>-->
 
        <link href="/css/reset.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/base.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/forms.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/import.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/datatables/demo_page.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/datatables/demo_table.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/smoothness/jquery-ui-1.10.1.custom.css" media="screen" rel="stylesheet" type="text/css" ><script type="text/javascript" src="/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.10.1.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="/js/base.js"></script>
<script type="text/javascript" src="/js/jquery.ui.datepicker-fr.js"></script>        
    </head>
    <body>
        <div id="body" class="white">
            <header>
    <p>DMA</p>
</header>            
            <div id="corps">         
                <div id="menuGauche" class="left" >
                    <ul>
                        <li><a href="/">Palmares</a></li>
                        <li><a href="/palmares/infosperiode">Palmares entre dates</a></li>
                        <li><a href="/index/tonnage">Tonnage</a></li>
                        <li><a href="/index/importer">Importer .csv</a>
                    </ul>
                </div>
                <div id="content" class="reste">  
                    <h2>Informations sur un conteneur</h2>
<div class="zend_form formConteneur">
 
<form enctype="application/x-www-form-urlencoded" action="/index/tonnage" method="post">
<div class="divform"><p id="sel_matiere-label"><label for="sel_matiere" class="spanform optional">Matiere :</label></p>
 
<select name="sel_matiere" id="sel_matiere" class="selec">
    <option value="Verre Couleur" selected="selected">Verre Couleur</option>
</select></div>
<div class="divform"><p id="nConteneur-label"><label for="nConteneur" class="spanform optional">Conteneur :</label></p>
 
<select name="nConteneur" id="nConteneur">
    <option value="P&gt;25683">P&gt;25683</option>
    <option value="P&gt;25684">P&gt;25684</option>
    <option value="P&gt;25685">P&gt;25685</option>
    <option value="P&gt;25687">P&gt;25687</option>
    <option value="P&gt;25688">P&gt;25688</option>
    <option value="P&gt;25673">P&gt;25673</option>
    <option value="P&gt;25675">P&gt;25675</option>
    <option value="P&gt;25676">P&gt;25676</option>
    <option value="P&gt;25677">P&gt;25677</option>
    <option value="P&gt;25678">P&gt;25678</option>
    <option value="P&gt;25679">P&gt;25679</option>
    <option value="P&gt;25681">P&gt;25681</option>
    <option value="P&gt;25682">P&gt;25682</option>
    <option value="P&gt;25686">P&gt;25686</option>
    <option value="P&gt;25689">P&gt;25689</option>
    <option value="P&gt;25690">P&gt;25690</option>
    <option value="P&gt;25691">P&gt;25691</option>
    <option value="P&gt;25693">P&gt;25693</option>
    <option value="P&gt;25694">P&gt;25694</option>
    <option value="P&gt;25695">P&gt;25695</option>
    <option value="P&gt;25697">P&gt;25697</option>
    <option value="P&gt;25698">P&gt;25698</option>
    <option value="P&gt;25699">P&gt;25699</option>
    <option value="P&gt;25700">P&gt;25700</option>
    <option value="P&gt;25702">P&gt;25702</option>
    <option value="P&gt;25703">P&gt;25703</option>
    <option value="P&gt;25704">P&gt;25704</option>
    <option value="P&gt;25705">P&gt;25705</option>
    <option value="P&gt;25706">P&gt;25706</option>
    <option value="P&gt;25707">P&gt;25707</option>
    <option value="P&gt;25709">P&gt;25709</option>
    <option value="P&gt;25710">P&gt;25710</option>
    <option value="P&gt;25711">P&gt;25711</option>
    <option value="P&gt;25712">P&gt;25712</option>
    <option value="P&gt;25713">P&gt;25713</option>
    <option value="P&gt;25714">P&gt;25714</option>
    <option value="P&gt;25715">P&gt;25715</option>
    <option value="P&gt;25716">P&gt;25716</option>
    <option value="P&gt;25717">P&gt;25717</option>
    <option value="P&gt;25718">P&gt;25718</option>
    <option value="P&gt;25719">P&gt;25719</option>
    <option value="P&gt;25720">P&gt;25720</option>
    <option value="P&gt;25721">P&gt;25721</option>
    <option value="P&gt;25722">P&gt;25722</option>
    <option value="P&gt;25723">P&gt;25723</option>
    <option value="P&gt;25724">P&gt;25724</option>
    <option value="P&gt;25725">P&gt;25725</option>
    <option value="P&gt;25726">P&gt;25726</option>
    <option value="P&gt;25729">P&gt;25729</option>
    <option value="P&gt;25730">P&gt;25730</option>
    <option value="P&gt;27069">P&gt;27069</option>
    <option value="P&gt;28483">P&gt;28483</option>
    <option value="P&gt;28642">P&gt;28642</option>
    <option value="P&gt;29120">P&gt;29120</option>
    <option value="P&gt;29127">P&gt;29127</option>
    <option value="P&gt;29128">P&gt;29128</option>
    <option value="P&gt;29289">P&gt;29289</option>
    <option value="P&gt;29339">P&gt;29339</option>
    <option value="P&gt;30778">P&gt;30778</option>
    <option value="P&gt;31063">P&gt;31063</option>
    <option value="P&gt;25773">P&gt;25773</option>
    <option value="P&gt;25772">P&gt;25772</option>
    <option value="P&gt;25759">P&gt;25759</option>
    <option value="P&gt;25782">P&gt;25782</option>
    <option value="P&gt;25781">P&gt;25781</option>
    <option value="P&gt;25650">P&gt;25650</option>
    <option value="P&gt;25777">P&gt;25777</option>
    <option value="P&gt;25638">P&gt;25638</option>
    <option value="P&gt;25670">P&gt;25670</option>
    <option value="P&gt;25668">P&gt;25668</option>
    <option value="P&gt;25651">P&gt;25651</option>
    <option value="P&gt;25640">P&gt;25640</option>
    <option value="P&gt;25637">P&gt;25637</option>
    <option value="P&gt;25771">P&gt;25771</option>
    <option value="P&gt;25788">P&gt;25788</option>
    <option value="P&gt;25654">P&gt;25654</option>
    <option value="P&gt;25652">P&gt;25652</option>
    <option value="P&gt;25641">P&gt;25641</option>
    <option value="P&gt;25665">P&gt;25665</option>
    <option value="P&gt;25649">P&gt;25649</option>
    <option value="P&gt;25648">P&gt;25648</option>
    <option value="P&gt;25672">P&gt;25672</option>
    <option value="P&gt;25671">P&gt;25671</option>
    <option value="P&gt;25664">P&gt;25664</option>
    <option value="P&gt;25662">P&gt;25662</option>
    <option value="P&gt;25734">P&gt;25734</option>
    <option value="P&gt;25663">P&gt;25663</option>
    <option value="P&gt;25653">P&gt;25653</option>
    <option value="P&gt;25661">P&gt;25661</option>
    <option value="P&gt;25708">P&gt;25708</option>
    <option value="P&gt;25728">P&gt;25728</option>
    <option value="P&gt;28640">P&gt;28640</option>
    <option value="P&gt;25770">P&gt;25770</option>
    <option value="P&gt;25733">P&gt;25733</option>
    <option value="P&gt;25737">P&gt;25737</option>
    <option value="P&gt;29297">P&gt;29297</option>
    <option value="P&gt;25739">P&gt;25739</option>
    <option value="P&gt;25740">P&gt;25740</option>
    <option value="P&gt;25741">P&gt;25741</option>
    <option value="P&gt;25742">P&gt;25742</option>
    <option value="P&gt;25743">P&gt;25743</option>
    <option value="P&gt;25775">P&gt;25775</option>
    <option value="P&gt;25778">P&gt;25778</option>
    <option value="P&gt;25779">P&gt;25779</option>
    <option value="P&gt;25783">P&gt;25783</option>
    <option value="P&gt;31031">P&gt;31031</option>
    <option value="P&gt;25784">P&gt;25784</option>
    <option value="P&gt;25785">P&gt;25785</option>
    <option value="P&gt;29784">P&gt;29784</option>
    <option value="P&gt;25754">P&gt;25754</option>
    <option value="P&gt;25755">P&gt;25755</option>
    <option value="P&gt;25757">P&gt;25757</option>
    <option value="P&gt;25758">P&gt;25758</option>
    <option value="P&gt;25760">P&gt;25760</option>
    <option value="P&gt;25761">P&gt;25761</option>
    <option value="P&gt;25762">P&gt;25762</option>
    <option value="P&gt;25763">P&gt;25763</option>
    <option value="P&gt;25744">P&gt;25744</option>
    <option value="P&gt;25745">P&gt;25745</option>
    <option value="P&gt;25764">P&gt;25764</option>
    <option value="P&gt;25767">P&gt;25767</option>
    <option value="P&gt;25768">P&gt;25768</option>
    <option value="P&gt;25746">P&gt;25746</option>
    <option value="P&gt;25748">P&gt;25748</option>
    <option value="P&gt;25750">P&gt;25750</option>
    <option value="P&gt;31032">P&gt;31032</option>
    <option value="P&gt;25753">P&gt;25753</option>
    <option value="P&gt;25769">P&gt;25769</option>
    <option value="P&gt;25634">P&gt;25634</option>
    <option value="P&gt;25635">P&gt;25635</option>
    <option value="P&gt;25636">P&gt;25636</option>
    <option value="P&gt;25639">P&gt;25639</option>
    <option value="P&gt;25642">P&gt;25642</option>
    <option value="P&gt;25643">P&gt;25643</option>
    <option value="P&gt;25645">P&gt;25645</option>
    <option value="P&gt;25646">P&gt;25646</option>
    <option value="P&gt;25657">P&gt;25657</option>
    <option value="P&gt;25666">P&gt;25666</option>
    <option value="P&gt;25667">P&gt;25667</option>
    <option value="P&gt;25669">P&gt;25669</option>
    <option value="P&gt;33898">P&gt;33898</option>
    <option value="P&gt;33899">P&gt;33899</option>
    <option value="P&gt;25656">P&gt;25656</option>
    <option value="P&gt;25696">P&gt;25696</option>
    <option value="P&gt;29649">P&gt;29649</option>
    <option value="P&gt;25774">P&gt;25774</option>
    <option value="P&gt;25776">P&gt;25776</option>
    <option value="P&gt;26940">P&gt;26940</option>
    <option value="P&gt;25674">P&gt;25674</option>
    <option value="P&gt;28902">P&gt;28902</option>
    <option value="P&gt;25786">P&gt;25786</option>
    <option value="P&gt;26943">P&gt;26943</option>
    <option value="P&gt;26575">P&gt;26575</option>
    <option value="P&gt;26944">P&gt;26944</option>
    <option value="P&gt;25727">P&gt;25727</option>
</select></div>
<div class="divdate">
<div class="divform"><p id="dateDebut-label"><label for="dateDebut" class="spanform optional">Date de debut :</label></p>
 
<input type="text" name="dateDebut" id="dateDebut" value="" class="datepicker cacher" autocomplete="off"></div>
<div class="divform"><p id="dateFin-label"><label for="dateFin" class="spanform optional">Date de fin :</label></p>
 
<input type="text" name="dateFin" id="dateFin" value="" class="datepicker cacher" autocomplete="off"></div></div>
<div class="divform"><p id="sub-label"><label for="sub" class="spanform optional">Envoyer</label></p>
 
<input type="submit" name="sub" id="sub" value="Envoyer" class="bt_submit"></div></form>    <div class="both"></div>
</div>
    <p id="msgInfosContenur">
        Selectionnez une matiere, pour avoir les conteneurs correspondants.<br />
        Vous pouvez spécifier une période, si vous ne le faites pas, les données 
        affichées iront de la date la plus ancienne à aujourd'hui.
    </p>
                </div>
            </div>
            <footer>
    <p>Kevin Verschaeve</p>
    <p>Application DMA | 2013 </p>
</footer>        </div>
    </body>
</html>