<head>
    <meta charset="UTF-8" />
    <script type="text/javascript" src="/js/jquery-1.9.1.js"></script>
    <script type='text/javascript'>
        $(document).ready(function() {
            $('#sel_communes').change(function() {
                var commune = $('#sel_communes').val();
                window.location = '/test/retest/sel_commune/'+commune;
            });
        });
    </script>
</head>
<?php
    echo $this->fcommunes;
?>
