<!DOCTYPE>
<html>
    <head>
        <title>DMA</title>
        <meta charset="utf-8" />
        <!--[if lt IE 8]>
            <link rel="stylesheet" href="/dma/public/css/specialIE.css" media="screen">
            <script type="text/javascript" src="/dma/public/js/html5.js"></script>
        <![endif]-->
        <link rel="icon" type="images/png" href="<?php echo $this->baseUrl();?>/img/favicon.ico" />
        
        <?php
            // CSS
            $this->headLink()->appendStylesheet($this->baseUrl('/css/reset.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/base.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/forms.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/import.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/regleConteneurs.css'));

            $this->headLink()->appendStylesheet($this->baseUrl('/css/datatables/demo_page.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/datatables/demo_table.css'));          
            $this->headLink()->appendStylesheet($this->baseUrl('/css/smoothness/jquery-ui-1.10.1.custom.css'));
            echo $this->headLink();
          
            // JAVASCRIPT
            $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.9.1.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery-ui-1.10.1.custom.min.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.dataTables.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/base.js'));
            //$this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.datepicker-fr.js'));
            echo $this->headScript();
        ?>
        <!-- ajoute les balises Html 5 aux navigateurs qui ne les ont pas -->
        <script type="text/javascript">
            document.createElement("header");
            document.createElement("footer");
            document.createElement("section");
            document.createElement("aside");
            document.createElement("nav");
            document.createElement("article");
            document.createElement("figure");
        </script>

    </head>
    <body>
        <div id="body" class="white">
            <?php echo $this->layout()->header; ?>
            
            <div id="corps">         
                <div id="menuGauche"  > <!-- class="left"-->
                    <ul>
                       <li><a href="<?php echo $this->baseUrl('/');?>">Palmarès</a></li><!--
                    --><li><a href="<?php echo $this->baseUrl('/palmares/infosperiode');?>">Palmarès pour une période</a></li><!--
                    --><li><a href="<?php echo $this->baseUrl('/index/tonnage');?>">Informations pour un site</a></li><!--
                    --><li><a href="<?php echo $this->baseUrl('/index/importer');?>">Importer .csv</a><!--
                    --><li><a href="<?php echo $this->baseUrl('/index/graphique');?>">Graphiques</a><!--
                    --><li><a href="<?php echo $this->baseUrl('/index/nouveausite');?>">Ajouter un site</a><!--
                    --><li><a href="<?php echo $this->baseUrl('/index/changeconteneur');?>">Admin</a>
                    </ul>
                </div>
                <div id="content" class="reste">  
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <?php echo $this->layout()->footer; ?>
        </div>
    </body>
</html>