<!DOCTYPE>
<html>
    <head>
        <title>DMA</title>
        <meta charset="utf-8" />
        
        <?php
            // CSS
            $this->headLink()->appendStylesheet($this->baseUrl('/css/base.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/forms.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/smoothness/jquery-ui-1.10.1.custom.css'));
            echo $this->headLink();
          
            // JAVASCRIPT
            $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.9.1.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery-ui-1.10.1.custom.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/base.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.datepicker-fr.js'));
            echo $this->headScript();
        ?>
        
    </head>
    <body>
        <div id="body" class="white">
            <?php echo $this->layout()->header; ?>
            
            <div id="content">                
                <div id="menuGauche">
                    <ul>
                        <li><a href="<?php echo $this->baseUrl('/');?>">Accueil</a></li>
                        <li><a href="<?php echo $this->baseUrl('/index/tonnage');?>">Tonnage</a></li>
                        <li><a href="<?php echo $this->baseUrl('/palmares/index');?>">Palmares</a></li>
                        <li><a href="<?php echo $this->baseUrl('/palmares/infosperiode');?>">Palmares entre dates</a></li>
                    </ul>
                </div>
                <?php echo $this->layout()->content; ?>
            </div>
            
            <?php echo $this->layout()->footer; ?>
        </div>
    </body>
</html>